name: My Pipeline with Failure

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        run: echo "Let's run a test"

  build:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v4
      - name: Build image (will fail)
        run: |
          echo "Building..."
          exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: ["test", "build"]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy image
        run: echo "Let's deploy the image"

  notify:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: failure()
    steps:
      - name: Notify build failure
        run: echo "Build failed! Notify team."
